[Virtual DOM 만들기] 신세한탄(신세희) 미션 제출합니다.
woowacourse/javascript-own-ui-library pull request #14
Opened 2021-10-18 14:41 UTC by shinsehantan

안녕하세요 피터!🧚🏼‍♂️
피터랑은 리뷰어나 페어로 한 번도 만난 적이 없는 것 같아서
너무 반갑네요!!!!!!!!!!!!!!

[데모페이지](https://shinsehantan.github.io/javascript-own-ui-library/index.html)

이번 미션은 개인적으로 너무 어려워서
카운터 앱을 동작하게 하는 것만을 목표로 했기 때문에
코드가 다소 지저분하고... 변화 대응에도 취약합니다...😢

diff 알고리즘은 구현하지 못해서 
상태가 변할 때마다 리렌더링하고 있고,
useState도 만들고 싶었지만... 따흑...

아무튼! 리뷰 잘 부탁드립니다. 🙇🏻‍♀️

![화면-기록-2021-10-18-오후-11 24 27](https://user-images.githubusercontent.com/67591151/137752501-eafc16ff-ac64-40ba-b2a7-6bd810c7290f.gif)

### 필수 요구사항

- [x] VirtualDOM 생성 팩토리 함수 구현 (aka createElement)
- [x] 렌더러 구현
- [x] 직접 구현한 렌더러와 VirtualDOM으로 Counter App 렌더링
- [ ] DOM Node 비교
- [x] 업데이트 DOM Node
- [x] 렌더링한 Counter App 동작시키기

### 심화 요구사항

- [ ] 문자열 기반의 JSX Parser 구현
- [ ] AST 처리 기반의 JSX Parser 구현
- [ ] 동일한 Element인 경우 Key 속성을 만들어 순서를 지정하도록 구현
- [ ] Router 구현 후 Query Parameter를 사용해 초기 값 정의

2021-10-18 16:15 UTC, bigsaigon333 commented on .prettierrc
> +  "useTabs": true
Tab 멈춰!! :no_entry_sign:

2021-10-21 18:12 UTC, iborymagic requested changes
안녕하세요 신세한탄~!
미션에서 처음 만나서 굉장히 반갑군요~~
브랜이 없어 바쁜 와중에도 멋지게 앱을 구현해주신 것 같아요!

한 가지 이슈가 있다면, 버튼 동작이 죠끔 이상하다는 것인데,
만약 button tag 안에 strong tag가 있다고 치면, button tag를 눌렀을 때는 
아주 멋지게 카운터가 잘 동작하다가 strong tag를 누르면 갑자기 전부 reset이 되어버립니다.
요 원인만 파악해서 고쳐주시고, 코멘트 남긴거 슥 훑어주시면 감사하겠습니당
그리곤 마저 얘기를 더 나눠봐요! ㅎㅎ

고생하셨어요!! 👍👍👍👍👍👍

2021-10-21 18:12 UTC, iborymagic commented on index.js
> +	counterButtons.addEventListener('click', (e) => handleCounterButtons(e));
```suggestion
	counterButtons.addEventListener('click', handleCounterButtons);
```
요렇게만 적어도 동작하지 않나용?

2021-10-21 18:12 UTC, iborymagic commented on shinse/shinse.js
> +	let childNode = document.createElement(element.tag);
요 친구에게 let을 사용한 이유가 궁금해요!

2021-10-21 18:12 UTC, iborymagic commented on shinse/shinse.js
> +			}
createNode는 children이 text 혹은 number일 때, 즉 가장 마지막 노드의 부모일 때 element를 만들어주는 함수인 것 같고, createWrapperNode는 그 외의 상황에서 사용하는 함수인 것 같은데, 혹시 맞나요?

2021-10-21 18:12 UTC, iborymagic commented on shinse/shinse.js
> +	let wrapperNode = createNode(element);
요기도 let이에용!

2021-10-22 06:49 UTC, shinsehantan commented on .prettierrc
> +  "useTabs": true
useTabs가 동동의 심기를 건드렸군요ㅋㅋㅋㅋㅋㅋ 
사실 저는 여기에 대해 진지하게 고민해본 적이 없었는데요. 
동동이 생각하는 멈춰야하는 이유가 뭔지 말해주실 수 있나요?

사실 찾아보다가 웃긴 자료를 두개나 봐서 공유합니다 :)

- [스페이스 사용하는 개발자들이 tab을 사용하는 개발자보다 연봉이 높다는 연구결과](https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/?_ga=2.188693934.743855730.1634877652-1885756750.1614609966)
- [드라마에 나온 '그' 논쟁](https://www.youtube.com/watch?v=SsoOG6ZeyUI)

2021-10-22 07:18 UTC, shinsehantan commented on .prettierrc
> +  "useTabs": true
그리고 정말 와닿지 않는 게 있어서 동동에게 추가질문 갑니다....
저는 우선 tab 사용 파인데요.
useTabs true와 false의 차이를 정말 잘 모르겠습니다.
설정과 관계없이 tab 사용은 잘 되거든요..! 
대체 이 설정이 가진 함축적 의미가 뭔가요?????????

2021-10-22 08:39 UTC, shinsehantan commented on index.js
> +	counterButtons.addEventListener('click', (e) => handleCounterButtons(e));
핸들러에서 e.target.id를 사용하고 있어서 evnet를 넘겨주지 않으면 동작하지 않았었는데, 지금은 로직을 바꿔서 요렇게 할 필요가 없어졌네요 :)

2021-10-22 08:39 UTC, shinsehantan commented on shinse/shinse.js
> +	let childNode = document.createElement(element.tag);
let을 사용할 필요가 전혀 없었던 부분인데, 이것저것 실험할 때 let이 필요했다가, 최종적으로 못바꿨던 부분이 아닌가 싶습니다ㅠㅠ
아래도 마찬가지로 다시 const로 바꿔두었습니다 :)

2021-10-22 08:39 UTC, shinsehantan commented on shinse/shinse.js
> +			}
네 맞습니다! 함수 이름이 불분명해서 혼란스러우셨을 것 같네요..!
createNode를 createLastNode로 리네이밍 해보았습니다!

2021-10-22 08:44 UTC, iborymagic commented on shinse/shinse.js
> +			}
올 감사합니다!

2021-10-22 08:53 UTC, bigsaigon333 commented on .prettierrc
> +  "useTabs": true
3대 500 미만인데 언더아머 잡는 멸치들을 잡으러 다니는 헬창처럼, 
tab으로 저장하는 사람들, EOL을 LF로 저장하지 않는 사람들을 잡으러 다니는 자경대를 구성하고 싶네요

![image](https://user-images.githubusercontent.com/31029000/138424547-3369afdc-1dbf-433a-b2e4-1b120e007527.png)

2021-10-22 09:03 UTC, bigsaigon333 commented on .prettierrc
> +  "useTabs": true
저 드라마는 조금 과장이 심한거 같은데, space파라고 해서 space키로만 인덴트를 타이핑하라는게 아니라, 
파일에 저장할 때 인덴트를 `0x0B` 로 하지 말고 `0x20` 하라는 뜻입니다 :laughing: 

`useTabs: false` 의 뜻은 유저가 tab 키를 누르던 space 키를 누르던, 인덴트는 space 로 바꿔서 저장하라는 뜻이에요

2021-10-22 09:04 UTC, bigsaigon333 commented on .prettierrc
> +  "useTabs": true
그러니까 신세한탄이 Tab 키를 사용하면서도, 인덴트는 space로 저장할 수 있어여!!! Tab 멈춰 :no_entry_sign:

2021-10-22 09:13 UTC, bigsaigon333 commented on .prettierrc
> +  "useTabs": true
왜 Tab과 space에 집착하느냐 하면... 사실 눈에 보기에는 똑같은 공백으로 보이지만..  에디터에 따라서 다르게 보일 수 있어요 

Tab키를 저장된 파일은  에디터 설정에 따라서 Tab 하나가 space 2개로 보이게 하거나 space 4개로 보일 수 있습니다. 
또 에디터에 따라서 2-depth 인덴트를 하나의 Tab으로 저장하기도 합니다. (유저에게 보여줄 때만 2-depth로 보여주면 되니까요)

그런데 무조건 space로 하면은, 그런 에디터 설정이나 유저의 재량권을 제한하게 되는데, 
저는 유저의 재량권을 제한하는 방향이 오히려 개발자 경험(DX)을 향상시킨다고 생각해서 space파입니다 :smile: 

Tab 을 쓴다면, space 2번(또는 4번) 쓸거를 Tab 1번으로 대체가능하므로 파일크기를 일부 줄일 수 있다는 장점이 있긴 한데... 뭐.. 그정도 파일 크기는 중요하다고 생각하지 않습니다 ㅎㅎ(Yarn berry 쓰는 시점에서 이미 repo 용량 따위야 ... :sweat_smile: )

2021-10-22 09:19 UTC, bigsaigon333 commented on .prettierrc
> +  "useTabs": true
아 근데 드라마 영상을 절반밖에 안보고 올렸는데, 뒤에 논쟁에 제가 하고 싶은 말이 다 담겨있네욬ㅋㅋ

2021-10-22 09:20 UTC, bigsaigon333 commented on .prettierrc
> +  "useTabs": true
emacs 얘기도 나오넼ㅋㅋ 

> 또 에디터에 따라서 2-depth 인덴트를 하나의 Tab으로 저장하기도 합니다. (유저에게 보여줄 때만 2-depth로 보여주면 되니까요)

emacs가 아마 이런 설정이 있었던 걸로 기억해서 적었어욬ㅋㅋ

2021-10-22 09:46 UTC, ddongule commented on .prettierrc
> +  "useTabs": true
우왕 신기해!!!!!!!!!!!!!!!!!!!!!!!!! 재밌네요!!!!!!!!!!!!!!!!!!!!!

2021-10-22 12:29 UTC, iborymagic approved these changes
고생하셨어용
이벤트 핸들러 코드의 변화가 인상적 👍👍
이제 아무런 문제 없이 잘 동작하므로
상태 관리 미션으로 넘어가보아용

2021-10-22 12:29 UTC, iborymagic commented on index.js
> +};
오오...
이벤트 핸들링 코드들이 이전보다 훨씬 더 깔끔해진듯
쩔었다 👍👍

2021-10-22 12:30 UTC, merged