[Virtual DOM 만들기] 주모(한준모) 미션 제출합니다
woowacourse/javascript-own-ui-library pull request #36
Opened 2021-11-23 11:32 UTC by jum0

먼저 카일 늦어서 죄송합니다ㅠ

https://user-images.githubusercontent.com/40762111/143012179-bc80f3fd-1174-4331-95f3-d1f884de7549.mov

- [x] VirtualDOM 생성 팩토리 함수 구현 (aka createElement)
- [x] 렌더러 구현
- [x] 직접 구현한 렌더러와 VirtualDOM으로 Counter App 렌더링
- [ ]  DOM Node 비교
- [x] 업데이트 DOM Node
- [x] 렌더링한 Counter App 동작시키기

전체적인 동작 방식은 다음과 같습니다.
1. render 함수가 두 가지 파라미터, elements(vDOM)와 이 vDOM을 적용할 루트 객체를 받습니다.
2. render 함수가 실행되기 이전에 elements는 createElement 함수를 통해 형태를 갖춘 vDOM이 됩니다.
3. render 함수 내에서 vDOM을 순회하면서 실제 DOM에 반영될 elements를 만듭니다.
4. 루트 객체에 적용(대체)합니다.

부족한 부분 있으면 알려주세요! 감사합니다!

2021-11-24 05:35 UTC, GwangYeol-Im requested changes
책임감 있는 주모! 안녕하세요 ㅎㅎ 과제 요구사항에 맞는 코드를 작성하려는 노력들이 코드에 잘 보여 좋았습니다 :) 상세 코멘트의 리뷰 확인해주시고 주모의 생각도 가감없이 말해주면 좋을 것 같아요~~ 1, 2단계 모두 올려주셨지만 차근차근 핑퐁 이어나갔으면 하는 바램으로 1단계만 우선 리뷰 남겨놓겠습니다!

2021-11-24 05:35 UTC, GwangYeol-Im commented on library/JuactDOM.js
> +      : element.setAttribute(key, value);
이 부분을 고칠 필요는 없지만, 개인적인 경험을 공유하고 싶어 코멘트 남깁니다!
```js
element[key] = value;
```
리액트에서는 js의 `class` 예약어와 혼동을 막기 위해 `className`을 사용하거나 몇 개의 속성을 camelCase로 작성 하길래 이걸 일일이 DOM으로 변환할 때 바꿔주는 줄 알았는데, 위의 코드처럼 해당 key에 할당을 하면 되더라구요!

2021-11-24 05:35 UTC, GwangYeol-Im commented on App.js
> +    render(elements(), document.getElementById('root'));
`App`에서 `element`와 `root` node를 알고 있는 부분이 다소 어색해보이는데, 이 부분은 리액트에서 저장하고 있어도 되지 않을까요??

2021-11-24 05:35 UTC, GwangYeol-Im commented on library/JuactDOM.js
> +  root.replaceChildren(fragment);
`document.createDocumentFragment()`를 이용해 따로 `fragment` node를 만들게 된 이유를 알 수 있을까요? 처음 코드를 읽었을 때, `fragment`의 내부에 변화가 일어나는 흐름이라 어떤 식으로 처리되는지 유추하면서 읽게 되더라구요!
```js
createDOM(vDOM, root) // attachToDOM이라는 이름도 생각해볼 수 있을 것 같네요
```
혹은,
```js
const dom = createDOM(vDOM, fragement);
root.replaceChildren(dom);
```
이런 식으로 DOM이 만들어지는 과정과 root node에 할당되는 흐름을 명시적으로 보여주면 좋을 것 같은데, 어떻게 생각하시나요? 😊

2021-11-24 11:23 UTC, jum0 commented on library/JuactDOM.js
> +      : element.setAttribute(key, value);
제가 제대로 이해를 못한 것 같은데, 26라인을 `(element[key] = value)` 이런 식으로 했을 때, class가 제대로 할당되지 않아 css 속성이 빠지는 것을 보니 제대로 동작하지 않는 것 같은데, 어떤 식으로 사용하면 될까요??

2021-11-24 11:46 UTC, jum0 commented on library/JuactDOM.js
> +  root.replaceChildren(fragment);
다른 노드를 붙이기 위한 기본적인 루트로 사용하기 위해서 해당 메서드를 사용했습니다!

그 외에 해당 메서드만이 가지는 특징을 사용하기 위함은 아니었는데, 찾아보니 `document.createDocumentFragment()`를 사용하면 빈 DocumentFragment를 만들어서 `createDOM` 함수를 지나면서 그 위에 쌓고, 실제 DOM에 추가하면 기존의 fragment에 쌓여있던 노드들이 사라져 메모리상에서 쉽게 조작할 수 있는 이점이 있다고 하네요!

그리고 제안주신 방법, 특히 아래 방법으로 코드를 변경하면 그 흐름을 파악하기 더 좋을 것 같습니다! 감사합니다!

2021-11-24 11:48 UTC, jum0 commented on App.js
> +    render(elements(), document.getElementById('root'));
`App`에서 `root` node를 알고 있고 있는 게 어색할 수 있다는 것에 동의합니다.  그런데, `elements` 함수는 실제로 리액트라고 했을 때 render 부분의 느낌으로 구현했는데 이 부분도 어색할까요??

그리고 리액트에서 저장하고 있어도 된다는 말을 잘 이해하지 못했어요ㅠ

2021-11-25 03:52 UTC, GwangYeol-Im commented on library/JuactDOM.js
> +      : element.setAttribute(key, value);
아, 그래서 고칠 필요가 없다는 말을 붙였습니다! 주모의 V-DOM 코드를 보면 현재 `class`라는 key를 가지고 있던데, 저는 `className` key를 주고 저런 식으로 할당하니 DOM에 적용이 되더라구요 ㅎㅎ 리액트도 이렇게 하지 않았을까 하는 생각에 공유한 거였습니다~!

2021-11-25 03:58 UTC, GwangYeol-Im commented on App.js
> +    render(elements(), document.getElementById('root'));
`그런데, elements 함수는 실제로 리액트라고 했을 때 render 부분의 느낌으로 구현했는데 이 부분도 어색할까요??`
- 리액트에서 리렌더를 시키기 위해서는 `setState()`를 사용하는데, 이때 저희가 넘겨주는 건 새로운 상태이지, 해당 컴포넌트의 V-DOM이 아니라고 생각해서 말씀드렸습니다 ㅎ.ㅎ 하지만 미션의 주제가 '나만의 상태 관리 라이브러리'이기 때문에 굳이 리액트를 따라갈 필요는 없어보이네요!!

`그리고 리액트에서 저장하고 있어도 된다는 말을 잘 이해하지 못했어요ㅠ`
- 초기에 앱을 렌더링할 때 V-DOM 전체와 root 노드를 넘겨주게 될 텐데, 이때 내부 상태로 가지고 있으면 되지 않을까? 하는 생각에서 말씀드린 거였습니다 ㅎㅎ

2021-11-25 04:04 UTC, GwangYeol-Im approved these changes
코드 수정 사항 잘 확인했습니다! UI 라이브러리를 만드는 과정은 결국 정답이 없다고 생각하기 때문에 서로의 의견을 주고받는 것만으로 좋은 것 같네요 :) 리뷰 한 번씩만 확인해보시고 다음 단계로 넘어가시죠~!

2021-11-25 04:18 UTC, merged